CREATE TABLE CARRIER_DETAILS
(
	CITY			VARCHAR2(30),
	CARRIER_NAME	VARCHAR2(30),
	CARRIER_RATING	NUMBER(10,2)
);

CREATE TABLE ORDER_DETAILS
(
	ORDER_NMBR	VARCHAR2(20),
	CUST_NAME	VARCHAR2(50),
	CITY		VARCHAR2(30),
	CUST_TYPE	VARCHAR2(10),
	CARRIER		VARCHAR2(30)
);